import {
  Utensils,
  Car,
  Home,
  Gamepad2,
  HeartPulse,
  GraduationCap,
  Briefcase,
  Laptop,
  Gift,
  Wallet,
  Banknote,
  Tag,
  ShoppingBag,
  ShoppingCart,
  Ticket,
  Coffee,
  Bus,
  Plane,
  Shirt,
  Music,
  BookOpen,
  Dumbbell,
  Baby,
  Smartphone,
  Zap,
  Landmark,
  Building2,
  CreditCard,
  CircleDollarSign,
  PiggyBank,
  Heart,
  Star,
  Truck,
  Tv,
  Droplets,
  MoreHorizontal,
} from "lucide-react";

const iconMap = {
  utensils: Utensils,
  car: Car,
  home: Home,
  gamepad2: Gamepad2,
  "heart-pulse": HeartPulse,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  laptop: Laptop,
  gift: Gift,
  wallet: Wallet,
  banknote: Banknote,
  tag: Tag,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  ticket: Ticket,
  coffee: Coffee,
  bus: Bus,
  plane: Plane,
  shirt: Shirt,
  music: Music,
  "book-open": BookOpen,
  dumbbell: Dumbbell,
  baby: Baby,
  smartphone: Smartphone,
  zap: Zap,
  landmark: Landmark,
  "building-2": Building2,
  "credit-card": CreditCard,
  "circle-dollar-sign": CircleDollarSign,
  "piggy-bank": PiggyBank,
  heart: Heart,
  star: Star,
  truck: Truck,
  tv: Tv,
  droplets: Droplets,
  "more-horizontal": MoreHorizontal,
};

export function categoryIcon(name) {
  const key = String(name || "").toLowerCase();
  return iconMap[key] || Tag;
}

export const ICON_CHOICES = Object.keys(iconMap);
